version: 2

sources:
  - name: arbitrum_decoded
    database: arbitrum
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp       

  - name: arbitrum_raw
    database: arbitrum
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp    
      - name: logs
        loaded_at_field: block_timestamp   

  - name: avalanche_decoded
    database: avalanche
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp        

  - name: avalanche_raw
    database: avalanche
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp   

  - name: base_decoded
    database: base
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp       

  - name: base_raw
    database: base
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp    
      - name: logs
        loaded_at_field: block_timestamp 

  - name: worldchain_decoded
    database: worldchain
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp       

  - name: worldchain_raw
    database: worldchain
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp    
      - name: logs
        loaded_at_field: block_timestamp 

  - name: ethereum_decoded
    database: ethereum
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp        

  - name: ethereum_raw
    database: ethereum
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp 

  - name: optimism_decoded
    database: optimism
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp   
      - name: logs
        loaded_at_field: block_timestamp      

  - name: optimism_raw
    database: optimism
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp

  - name: polygon_decoded
    database: polygon
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp        

  - name: polygon_raw
    database: polygon
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp  

  - name: bsc_decoded
    database: bsc
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp        

  - name: bsc_raw
    database: bsc
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp     

  - name: linea_decoded
    database: linea
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp     

  - name: linea_raw
    database: linea
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp  
      - name: logs
        loaded_at_field: block_timestamp      

  - name: mantle_decoded
    database: mantle
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp     

  - name: mantle_raw
    database: mantle
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp  
      - name: logs
        loaded_at_field: block_timestamp   

  - name: celo_decoded
    database: celo
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp     

  - name: celo_raw
    database: celo
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp  
      - name: logs
        loaded_at_field: block_timestamp   

  - name: arbitrum_nova_decoded
    database: arbitrum_nova
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp     

  - name: arbitrum_nova_raw
    database: arbitrum_nova
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp  
      - name: logs
        loaded_at_field: block_timestamp  

  - name: gnosis_decoded
    database: gnosis
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp    

  - name: gnosis_raw
    database: gnosis
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp    
      - name: logs
        loaded_at_field: block_timestamp 

  - name: common_prices
    database: common
    schema: prices
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: hourly
        loaded_at_field: timestamp 

  - name: common_decoded
    database: common
    schema: decoded
    tables:
      - name: function_signatures             